// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUzczjL1eO_-eVO67peSe0a-WwKwDwQ0Q',
    appId: '1:200788123597:web:04798cb5204e275b7bee84',
    messagingSenderId: '200788123597',
    projectId: 'tripsflutterapp-fd3d4',
    authDomain: 'tripsflutterapp-fd3d4.firebaseapp.com',
    storageBucket: 'tripsflutterapp-fd3d4.appspot.com',
    measurementId: 'G-TQ7CSB1PSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUy7ZAKGW_9kPcXDKSPjugs-NC2okYjDg',
    appId: '1:200788123597:android:4184bc8a0eaeb1ab7bee84',
    messagingSenderId: '200788123597',
    projectId: 'tripsflutterapp-fd3d4',
    storageBucket: 'tripsflutterapp-fd3d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFV6cm8ja0Cz-E_pwgLcx1_z3xwmB4qeU',
    appId: '1:200788123597:ios:7d08a753e2e259477bee84',
    messagingSenderId: '200788123597',
    projectId: 'tripsflutterapp-fd3d4',
    storageBucket: 'tripsflutterapp-fd3d4.appspot.com',
    androidClientId:
        '200788123597-318upgn5g9c6uk32br4uc6ovpbjv2jic.apps.googleusercontent.com',
    iosClientId:
        '200788123597-vk9nq89cnqhvh9gj10pa7h4varl83ae0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripsApp',
  );
}
